# Интересный факт - согласно доке, предпочтительно использовать нейминг и расширение файла compose.yaml
# "Compose prefers the canonical compose.yaml"
# https://docs.docker.com/compose/intro/compose-application-model/

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: junior-devops-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_ENV: ${APP_ENV}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${PORT}/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
